export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCESS = "FETCH_PRODUCTS_SUCESS";
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";
export const FETCH_FEATURED_PRODUCTS_SUCESS = "FETCH_FEATURED_PRODUCTS_SUCESS";
export const FETCH_MATERIAL_SUCESS = "FETCH_MATERIAL_SUCESS";
export const ADDtOCART_SUCESS = "ADDtOCART_SUCESS";
export const FILTER_MATERIAL_PRODUCT = "FILTER_MATERIAL_PRODUCT";
export const FILTER_COLOR_PRODUCT = "FILTER_COLOR_PRODUCT";
export const FETCH_COLOR_SUCESS="FETCH_COLOR_SUCESS";

export const URL =
    "https://api.sheety.co/af35b536915ec576818d468cf2a6505c/reactjsTest";
export const token = "Ex9yLyRU7wvyxfblpq5HAhfQqUP1vIyo ";
